### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nikett** [ggerganov/dot-to-ascii#5]
I plan to use dot-to-ascii service to collect human annotations on the ASCII graphs generated by Graph::Easy, and for simplicity, I would use your useful wrapper. I made the ASCII graphs "interactive" with dropdowns and boxes so that annotations can be provided by users and a backend can store them. I want to ask for your permission to use dot-to-ascii web service and learn if there is any license associated with using your wrapper service? 

There are fancier graph approaches such as cytoscape to render interactive graphs, but for very simple use cases such as for researchers who are evaluating graphs automatically generated by their model, the ascii annotation experience is ok and has no overhead.

**Comment by ggerganov** [comment]
The code in this repository is licensed with MIT License - I just added the [LICENSE](https://github.com/ggerganov/dot-to-ascii/blob/master/LICENSE) file.

The service is completely free to use by anyone and there is no license associated with it.
I plan to keep it running for as long as possible.

**Comment by nikett** [comment]
Thanks, much appreciated!
