### ISSUE TITLE
Command-line execution? (enhancement request? doc?)

### ISSUE THREAD

**Issue by sarnobat** [ggerganov/dot-to-ascii#7]
This tool looks better than graph-easy but I don't wish to use a browser interface. Is there a way to run this as follows?

```
dot2ascii input.dot > output.txt
```

If it gets introduced, I will probably start using it instead of graph-easy.

**Comment by ggerganov** [comment]
Maybe you want this:

`dot2ascii  --as_boxart input.dot > output.txt`

**Comment by sarnobat** [comment]
Is dot2ascii a command? Actually I just realized that your php code executes `graph-easy --from=dot --as_ascii` which does eactly what I want. Closing. Thanks for the quick response.
